---
id: rubykansai78-gitlab-dokku
base_name: gitlab-dokku
tags:
- gitlab
- dokku
presentation_date: 2017/07/29
version: 2017.07.29
licenses: []
slideshare_id:
speaker_deck_id:
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
